#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::JSON;
use Mojo::Log;
use Data::Dumper;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

post '/github' => sub{
    my $self = shift;
    my $log = Mojo::Log->new(path=>'./log');

    $log->debug( Dumper($self) );
    $log->debug( $self->param);
    $log->debug( $self->param('payload') );
    $self->render(text => 'good', status=>200);
};

app->start;

__DATA__

@@ github.html.ep
% title 'good';

